### ISSUE TITLE
Websocket

### ISSUE THREAD

**Issue by Mylloon** [Celeo/mattermost_api#1]
Hello,

Is there an ETA on the release of websocket support?

**Comment by Celeo** [comment]
Hiya,

I'll take a look at what kind of work implementing websocket support would take this weekend.

**Comment by Celeo** [comment]
Hey,
I pushed some **really basic** websocket stuff in v0.2.0. I've never been so confused with futures and types, but it seems to work. Nothing's typed yet, it's just strings. I'll plug away at it some more in the next few days.

**Comment by Celeo** [comment]
v0.3.0 has some more type information. Not _all_; there's a bit of `serde_json::Value` in there, but it's better than it was.

**Comment by Celeo** [comment]
Closing this, but feel free to open another issue if there's anything you need.
